# Generated by Django 4.1.7 on 2023-06-08 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_doctors_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctors_wanted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctor'),
        ),
    ]
