# Generated by Django 4.1.7 on 2023-06-08 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_appointment_doctors_wanted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
