# Generated by Django 4.1.7 on 2023-06-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Denied', 'Denied')], default='pending', max_length=50),
        ),
    ]
